import db, { createAlternative, createCrawlerSource } from '../src/lib/db';

// Comprehensive seed of OpenClaw alternatives and agentic AI assistants
const seedData = [
  // === CLAW FAMILY VARIANTS ===
  {
    name: 'OpenClaw',
    description: 'Original viral AI agent with multi-channel support (WhatsApp, Telegram, Slack, Discord).',
    fullDescription: 'The original OpenClaw project that started it all. A viral AI agent that gained massive popularity for its ability to connect to multiple communication channels. Supports WhatsApp, Telegram, Slack, Discord, and more.',
    githubUrl: 'https://github.com/openclaw-ai/openclaw',
    stars: 219000,
    language: 'TypeScript',
    category: 'popular',
    security: 'standard',
    deployment: ['cloud', 'docker', 'local'],
    hardware: ['x86_64', 'arm64', 'cloud-only'],
    useCases: ['personal', 'automation', 'enterprise'],
    features: ['Multi-channel support', 'WhatsApp', 'Telegram', 'Slack', 'Discord', 'Active community'],
  },
  {
    name: 'NullClaw',
    description: 'Fastest and smallest Claw variant at 678KB, boots in 2ms, fully autonomous.',
    fullDescription: 'Written in Zig, NullClaw claims to be the fastest and smallest AI agent available. With a binary size of just 678KB and boot time of 2ms, it is designed for ultra-high-performance scenarios.',
    githubUrl: 'https://github.com/nullclaw/nullclaw',
    stars: null,
    language: 'Zig',
    category: 'lightweight',
    security: 'minimal-permissions',
    deployment: ['local', 'embedded'],
    hardware: ['x86_64', 'arm64', 'risc-v'],
    useCases: ['personal', 'development', 'automation'],
    features: ['Ultra-fast', 'Small binary', '2ms boot time', 'Fully autonomous'],
  },
  {
    name: 'ZeroClaw',
    description: 'Production-grade Rust agent with 99% less memory than OpenClaw, sub-10ms startup.',
    fullDescription: 'A production-ready Rust-based AI agent designed for efficiency. Uses 99% less memory than OpenClaw and starts up in under 10ms. Perfect for production deployments requiring reliability and speed.',
    githubUrl: 'https://github.com/theonlyhennygod/zeroclaw',
    stars: 18877,
    language: 'Rust',
    category: 'lightweight',
    security: 'workspace-isolation',
    deployment: ['local', 'docker', 'embedded'],
    hardware: ['x86_64', 'arm64', 'esp32', 'raspberry-pi', 'risc-v'],
    useCases: ['personal', 'enterprise', 'automation', 'iot'],
    features: ['Ultra-low RAM', 'Rust-based', 'Sub-10ms startup', 'Production-ready'],
  },
  {
    name: 'PicoClaw',
    description: 'Ultra-low resource agent for $10 hardware like Raspberry Pi and RISC-V boards.',
    fullDescription: 'Designed specifically for budget hardware. PicoClaw runs on Raspberry Pi and RISC-V boards costing as little as $10, making AI agents accessible to hobbyists and IoT projects.',
    githubUrl: 'https://github.com/sipeed/picoclaw',
    stars: null,
    language: 'Go',
    category: 'hardware',
    security: 'minimal-permissions',
    deployment: ['local', 'embedded'],
    hardware: ['raspberry-pi', 'risc-v', 'esp32'],
    useCases: ['personal', 'iot', 'embedded', 'automation'],
    features: ['Budget hardware', 'Raspberry Pi', 'RISC-V support', 'Low resource'],
  },
  {
    name: 'NanoClaw',
    description: 'Docker and Apple Container isolation with security-focused design.',
    fullDescription: 'A security-focused variant of OpenClaw that uses Docker and Apple Container isolation. Designed for users who prioritize security and sandboxing in their AI agents.',
    githubUrl: 'https://github.com/qwibitai/nanoclaw',
    stars: 7000,
    language: 'TypeScript',
    category: 'security',
    security: 'sandboxed',
    deployment: ['docker', 'local', 'cloud'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['personal', 'enterprise', 'development'],
    features: ['Container isolation', 'Security-focused', 'Docker support', 'Apple Container'],
  },
  {
    name: 'IronClaw',
    description: 'WASM sandbox with credential protection and prompt injection defense.',
    fullDescription: 'Built with WebAssembly sandboxing, IronClaw provides enterprise-grade security features including credential protection, prompt injection defense, and memory safety.',
    githubUrl: 'https://github.com/nearai/ironclaw',
    stars: null,
    language: 'Rust',
    category: 'security',
    security: 'sandboxed',
    deployment: ['local', 'cloud', 'docker'],
    hardware: ['x86_64', 'arm64', 'cloud-only'],
    useCases: ['enterprise', 'development', 'automation'],
    features: ['WASM sandbox', 'Credential protection', 'Prompt injection defense', 'Memory safety'],
  },
  {
    name: 'Nanobot',
    description: 'Ultra-lightweight Python agent with ~4K lines of auditable code.',
    fullDescription: 'A popular open-source AI agent built in Python, known for its lightweight and auditable codebase. With approximately 4,000 lines of code, it offers transparency and ease of modification.',
    githubUrl: 'https://github.com/nanobot-ai/nanobot',
    stars: 24793,
    language: 'Python',
    category: 'popular',
    security: 'workspace-isolation',
    deployment: ['local', 'docker'],
    hardware: ['x86_64', 'arm64', 'raspberry-pi'],
    useCases: ['personal', 'development', 'automation'],
    features: ['Lightweight', 'Auditable', 'Python-based', 'Customizable', 'Active community'],
  },
  {
    name: 'TinyClaw',
    description: 'Minimal shell script agent with only 400 lines, research-focused.',
    fullDescription: 'An extremely minimalist AI agent written in just 400 lines of shell script. Designed for research purposes and users who want to understand the fundamentals of AI agents.',
    githubUrl: 'https://github.com/warengonzaga/tinyclaw',
    stars: null,
    language: 'Shell',
    category: 'lightweight',
    security: 'minimal-permissions',
    deployment: ['local'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['personal', 'research', 'development'],
    features: ['Minimalist', '400 lines', 'Research-focused', 'Shell-based'],
  },
  {
    name: 'MimiClaw',
    description: 'ESP32-S3 microcontroller agent ($5 chip) with voice capabilities.',
    fullDescription: 'An embedded AI agent designed for the ESP32-S3 microcontroller. At just $5 per chip, it brings AI agents to the world of embedded systems and voice-enabled IoT devices.',
    githubUrl: 'https://github.com/memovai/mimiclaw',
    stars: null,
    language: 'C',
    category: 'hardware',
    security: 'minimal-permissions',
    deployment: ['embedded'],
    hardware: ['esp32'],
    useCases: ['iot', 'embedded', 'automation'],
    features: ['ESP32-S3', 'Voice-enabled', '$5 chip', 'Microcontroller'],
  },
  {
    name: 'Moltis',
    description: 'Rust-native one binary agent with sandboxing, security, and auditability.',
    fullDescription: 'A Rust-native AI agent that ships as a single binary. Features sandboxed execution, security-first design, and full auditability for enterprise deployments.',
    githubUrl: 'https://github.com/moltis-org/moltis',
    stars: null,
    language: 'Rust',
    category: 'popular',
    security: 'sandboxed',
    deployment: ['local', 'docker', 'cloud'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['personal', 'enterprise', 'development', 'automation'],
    features: ['Single binary', 'Rust-native', 'Sandboxed', 'Auditable'],
  },
  {
    name: 'Moltworker',
    description: 'Cloudflare Workers deployment for serverless AI agents.',
    fullDescription: 'Built on Cloudflare Workers for fully serverless deployment. Moltworker allows you to run AI agents at the edge with global distribution and pay-per-request pricing.',
    githubUrl: 'https://github.com/cloudflare/moltworker',
    stars: null,
    language: 'TypeScript',
    category: 'lightweight',
    security: 'sandboxed',
    deployment: ['serverless', 'cloud'],
    hardware: ['cloud-only'],
    useCases: ['personal', 'enterprise', 'automation'],
    features: ['Cloudflare Workers', 'Serverless', 'Edge deployment', 'Pay-per-request'],
  },
  {
    name: 'memU',
    description: 'Long-term memory and knowledge graph agent for 24/7 proactive AI.',
    fullDescription: 'An AI agent focused on long-term memory and knowledge graph construction. Runs 24/7 and proactively learns from interactions to build a comprehensive knowledge base.',
    githubUrl: 'https://github.com/NevaMind-AI/memU',
    stars: 6900,
    language: 'Python',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'cloud', 'docker'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['personal', 'enterprise', 'automation'],
    features: ['Long-term memory', 'Knowledge graph', '24/7 operation', 'Proactive learning'],
  },
  {
    name: 'zclaw',
    description: '888 KiB binary for ESP32 with GPIO control capabilities.',
    fullDescription: 'A compact AI agent for ESP32 microcontrollers with GPIO control. At just 888 KiB, it brings AI capabilities to hardware projects with physical I/O control.',
    githubUrl: 'https://github.com/tnm/zclaw',
    stars: null,
    language: 'C',
    category: 'hardware',
    security: 'minimal-permissions',
    deployment: ['embedded'],
    hardware: ['esp32'],
    useCases: ['iot', 'embedded', 'automation'],
    features: ['GPIO control', 'ESP32', '888 KiB', 'Physical I/O'],
  },

  // === OTHER NOTABLE ALTERNATIVES ===
  {
    name: 'TrustClaw',
    description: 'OAuth-based agent with sandboxed execution and 1,000+ tools.',
    fullDescription: 'A security-first AI agent featuring OAuth authentication, sandboxed execution environment, and access to over 1,000 tools for various automation tasks.',
    githubUrl: 'https://github.com/trustclaw/trustclaw',
    stars: null,
    language: 'TypeScript',
    category: 'security',
    security: 'sandboxed',
    deployment: ['cloud', 'local', 'docker'],
    hardware: ['x86_64', 'arm64', 'cloud-only'],
    useCases: ['enterprise', 'automation', 'personal'],
    features: ['OAuth', 'Sandboxed execution', '1000+ tools', 'Security-first'],
  },
  {
    name: 'AgentZero',
    description: 'Autonomous agent for complex coding, research, and multi-step tasks.',
    fullDescription: 'A general-purpose autonomous AI agent capable of handling complex coding tasks, research, and multi-step operations. Designed as a flexible personal assistant.',
    githubUrl: 'https://github.com/agent0ai/agent-zero',
    stars: null,
    language: 'Python',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'cloud', 'docker'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['personal', 'development', 'automation', 'research'],
    features: ['Autonomous', 'Multi-step tasks', 'Coding', 'Research'],
  },
  {
    name: 'antfarm',
    description: 'Build your agent team in OpenClaw with one command.',
    fullDescription: 'A tool for quickly deploying teams of AI agents using OpenClaw. Create multi-agent systems with a single command for collaborative task completion.',
    githubUrl: 'https://github.com/snarktank/antfarm',
    stars: null,
    language: 'TypeScript',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'cloud', 'docker'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['personal', 'development', 'automation'],
    features: ['Multi-agent', 'Team deployment', 'One-command setup', 'Collaborative'],
  },
  {
    name: 'opengoat',
    description: 'Build AI autonomous organizations of OpenClaw agents.',
    fullDescription: 'A framework for creating autonomous organizations of AI agents. Multiple OpenClaw agents work together in coordinated roles to complete complex tasks.',
    githubUrl: 'https://github.com/marian2js/opengoat',
    stars: null,
    language: 'Python',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'cloud', 'docker'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['personal', 'development', 'enterprise', 'automation'],
    features: ['Multi-agent', 'Organization', 'Autonomous', 'Coordination'],
  },

  // === POPULAR AI AGENT FRAMEWORKS ===
  {
    name: 'LangChain',
    description: 'Most popular Python/JS framework for building LLM-powered applications.',
    fullDescription: 'The most widely used framework for building applications powered by large language models. Provides abstractions for chains, agents, and memory systems.',
    githubUrl: 'https://github.com/langchain-ai/langchain',
    stars: 122850,
    language: 'Python',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'cloud', 'docker'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['development', 'automation', 'enterprise', 'research'],
    features: ['LLM integration', 'Chains', 'Agents', 'Memory', 'Tools'],
  },
  {
    name: 'MetaGPT',
    description: 'Multi-agent collaboration framework for complex tasks.',
    fullDescription: 'A framework that enables multiple AI agents to collaborate on complex tasks. Agents can take on different roles like product manager, architect, and developer.',
    githubUrl: 'https://github.com/geekan/MetaGPT',
    stars: 61919,
    language: 'Python',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'cloud', 'docker'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['development', 'automation', 'research'],
    features: ['Multi-agent', 'Role-based', 'Collaboration', 'SOPs'],
  },
  {
    name: 'AutoGen',
    description: 'Microsoft framework for building multi-agent applications.',
    fullDescription: 'Microsoft\'s open-source framework for building applications with multiple AI agents that can work together autonomously.',
    githubUrl: 'https://github.com/microsoft/autogen',
    stars: 52927,
    language: 'Python',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'cloud', 'docker'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['development', 'automation', 'enterprise'],
    features: ['Multi-agent', 'Microsoft', 'Conversational', 'Customizable'],
  },
  {
    name: 'CrewAI',
    description: 'Multi-agent orchestration framework for AI workflows.',
    fullDescription: 'A framework for orchestrating multiple AI agents to work together on complex tasks. Popular for building AI-powered workflows.',
    githubUrl: 'https://github.com/crewAIInc/crewAI',
    stars: 30000,
    language: 'Python',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'cloud', 'docker'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['automation', 'development', 'enterprise'],
    features: ['Multi-agent', 'Orchestration', 'Workflows', 'Role-based'],
  },
  {
    name: 'LangGraph',
    description: 'LangChain ecosystem for building agentic and multi-agent applications.',
    fullDescription: 'Part of the LangChain ecosystem, LangGraph provides tools for building stateful, multi-actor applications with cycles.',
    githubUrl: 'https://github.com/langchain-ai/langgraph',
    stars: 24800,
    language: 'Python',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'cloud', 'docker'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['development', 'automation', 'enterprise'],
    features: ['Stateful', 'Cycles', 'Multi-agent', 'LangChain ecosystem'],
  },
  {
    name: 'LlamaIndex',
    description: 'Data framework for connecting LLMs to your data.',
    fullDescription: 'A data framework specifically designed to help LLMs access and reason over your private data. Essential for building knowledge-augmented agents.',
    githubUrl: 'https://github.com/run-llama/llama_index',
    stars: 35000,
    language: 'Python',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'cloud', 'docker'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['development', 'research', 'enterprise'],
    features: ['Data indexing', 'RAG', 'Knowledge base', 'Private data'],
  },

  // === SELF-HOSTED AI PLATFORMS ===
  {
    name: 'LocalAI',
    description: 'Drop-in OpenAI replacement for self-hosted AI.',
    fullDescription: 'A self-hosted, drop-in replacement for OpenAI API. Run LLMs locally with OpenAI-compatible API endpoints.',
    githubUrl: 'https://github.com/mudler/LocalAI',
    stars: null,
    language: 'Go',
    category: 'enterprise',
    security: 'standard',
    deployment: ['local', 'docker'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['personal', 'enterprise', 'development'],
    features: ['OpenAI compatible', 'Self-hosted', 'Local LLMs', 'API'],
  },
  {
    name: 'Ollama',
    description: 'Run large language models locally on your machine.',
    fullDescription: 'An easy way to get started running large language models locally. Download and run Llama, Mistral, and other models with a single command.',
    githubUrl: 'https://github.com/ollama/ollama',
    stars: null,
    language: 'Go',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'desktop'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['personal', 'development'],
    features: ['Local LLMs', 'Easy setup', 'CLI', 'Model library'],
  },
  {
    name: 'Open WebUI',
    description: 'Extensible self-hosted AI interface.',
    fullDescription: 'A feature-rich, extensible self-hosted AI interface. Connect to Ollama, LLMs, and build your own AI assistant.',
    githubUrl: 'https://github.com/open-webui/open-webui',
    stars: null,
    language: 'TypeScript',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'docker', 'cloud'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['personal', 'enterprise', 'development'],
    features: ['Web UI', 'Extensible', 'Ollama integration', 'RAG'],
  },
  {
    name: 'Anything LLM',
    description: 'Enterprise-ready document chatbot platform.',
    fullDescription: 'A full-stack document chatbot platform for enterprises. Upload documents and chat with them using LLMs.',
    githubUrl: 'https://github.com/Mintplex-Labs/anything-llm',
    stars: null,
    language: 'TypeScript',
    category: 'enterprise',
    security: 'standard',
    deployment: ['local', 'docker', 'cloud'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['enterprise', 'personal', 'development'],
    features: ['Document chat', 'RAG', 'Workspace', 'Multi-user'],
  },
  {
    name: 'OpenCode',
    description: 'Model-agnostic coding agent with 48K stars.',
    fullDescription: 'An open-source coding agent that works with multiple models. Designed for autonomous code generation and software development.',
    githubUrl: 'https://github.com/xingyaoww/open-code',
    stars: 48000,
    language: 'TypeScript',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'cloud', 'docker'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['development', 'automation'],
    features: ['Coding agent', 'Model-agnostic', 'Autonomous', '48K stars'],
  },
  {
    name: 'GPT4All',
    description: 'Run open-source LLMs locally on any device.',
    fullDescription: 'A free, open-source ecosystem to experiment with large language models locally. Runs on CPU with no GPU required.',
    githubUrl: 'https://github.com/nomic-ai/gpt4all',
    stars: null,
    language: 'Python',
    category: 'popular',
    security: 'standard',
    deployment: ['local', 'desktop'],
    hardware: ['x86_64', 'arm64'],
    useCases: ['personal', 'development'],
    features: ['CPU-friendly', 'Local LLMs', 'No GPU required', 'Open-source'],
  },
];

console.log('Seeding database...');

for (const data of seedData) {
  try {
    createAlternative({
      name: data.name,
      description: data.description,
      fullDescription: data.fullDescription,
      githubUrl: data.githubUrl,
      language: data.language,
      category: data.category,
      security: data.security,
      deployment: data.deployment,
      hardware: data.hardware,
      useCases: data.useCases,
      features: data.features,
      submittedBy: 'system',
    });

    // Update stars if available
    if (data.stars) {
      const slug = data.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      db.prepare('UPDATE alternatives SET stars = ? WHERE slug = ?').run(data.stars, slug);
    }

    // Update status to approved for seed data
    const slug = data.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    db.prepare('UPDATE alternatives SET status = ? WHERE slug = ?').run('approved', slug);

    console.log(`Created: ${data.name}`);
  } catch (error) {
    console.error(`Failed to create ${data.name}:`, error);
  }
}

// Seed default crawler sources
console.log('\nSeeding crawler sources...');

const defaultSources = [
  {
    name: 'OpenClaw GitHub',
    type: 'rss' as const,
    url: 'https://github.com/openclaw-ai/openclaw/releases.atom',
  },
  {
    name: 'r/LocalLLaMA',
    type: 'subreddit' as const,
    url: 'https://reddit.com/r/LocalLLaMA.json',
  },
  {
    name: 'r/Artificial',
    type: 'subreddit' as const,
    url: 'https://reddit.com/r/Artificial.json',
  },
  {
    name: 'Hacker News',
    type: 'api' as const,
    url: 'https://hacker-news.firebaseio.com/v0/topstories.json',
  },
];

for (const source of defaultSources) {
  try {
    createCrawlerSource({
      name: source.name,
      type: source.type,
      url: source.url,
      active: true,
    });
    console.log(`Created crawler source: ${source.name}`);
  } catch (error) {
    console.error(`Failed to create crawler source ${source.name}:`, error);
  }
}

console.log('Seeding complete!');
